language: python
sudo: false
cache:
  directories:
    - ~/.cache/pip
env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - pip install -U pip setuptools --upgrade
  - pip install wheel
install:
  - pip install numpy>=1.9 Cython
  - pip install -r requirements_dev.txt
  - pip install coveralls
  - pip install -e .
script: py.test --cov rasterstats --cov-report term-missing
after_success:
  - coveralls

